export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"Fira Code"', '"Cascadia Code"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      colors: {
        surface: {
          canvas: 'var(--surface-canvas)',
          page: 'var(--surface-page)',
          card: 'var(--surface-card)',
          elevated: 'var(--surface-elevated)',
          raised: 'var(--surface-raised)',
          muted: 'var(--surface-muted)',
          hover: 'var(--hover-bg)',
        },
        text: {
          primary: 'var(--text-primary)',
          heading: 'var(--text-heading)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          muted: 'var(--text-muted)',
          faint: 'var(--text-faint)',
        },
        border: {
          DEFAULT: 'var(--border-default)',   // enables `border-border` without opacity modifier
          subtle: 'var(--border-subtle)',
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
        },
        semantic: {
          bullish: 'var(--bullish)',
          'bullish-bg': 'var(--bullish-bg)',
          'bullish-border': 'var(--bullish-border)',
          bearish: 'var(--bearish)',
          'bearish-bg': 'var(--bearish-bg)',
          'bearish-border': 'var(--bearish-border)',
          warning: 'var(--warning)',
          'warning-bg': 'var(--warning-bg)',
          'warning-border': 'var(--warning-border)',
          accent: 'var(--accent)',
          'accent-bg': 'var(--accent-bg)',
          'accent-border': 'var(--accent-border)',
          info: 'var(--info)',
          'info-bg': 'var(--info-bg)',
          'info-border': 'var(--info-border)',
          neutral: 'var(--neutral)',
          'neutral-bg': 'var(--neutral-bg)',
          'neutral-border': 'var(--neutral-border)',
          manage: 'var(--manage)',
          'manage-bg': 'var(--manage-bg)',
          'manage-border': 'var(--manage-border)',
          supportive: 'var(--supportive)',
          'supportive-bg': 'var(--supportive-bg)',
          'supportive-border': 'var(--supportive-border)',
          conflict: 'var(--conflict)',
          'conflict-bg': 'var(--conflict-bg)',
          'conflict-border': 'var(--conflict-border)',
          extended: 'var(--extended)',
          'extended-bg': 'var(--extended-bg)',
          'extended-border': 'var(--extended-border)',
        },
      },
    },
  },
  plugins: [],
}
