"""
alpaca_trader.py — Alpaca Paper Trading Integration
====================================================
Connects to Alpaca's Paper Trading API to place multi-leg options orders
generated by the OptionAdvisor engine.

API docs: https://docs.alpaca.markets/reference/getallorders
Paper base URL: https://paper-api.alpaca.markets

OCC Symbol format: TICKER + YYMMDD + C/P + 8-digit strike (thousandths, zero-padded)
  Example: AAPL 190.0 CALL 2024-01-19 → AAPL240119C00190000
"""

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Optional

import httpx
from dotenv import load_dotenv

# ─────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────

ALPACA_PAPER_BASE = "https://paper-api.alpaca.markets"
ALPACA_DATA_BASE  = "https://data.alpaca.markets"

def _get_creds() -> tuple[str, str]:
    # Same directory as main.py .env — reload so edits apply without restarting (local dev).
    load_dotenv(Path(__file__).with_name(".env"), override=True)
    key    = os.getenv("ALPACA_API_KEY", "").strip()
    secret = os.getenv("ALPACA_SECRET_KEY", "").strip()
    return key, secret

def _headers() -> dict:
    key, secret = _get_creds()
    return {
        "APCA-API-KEY-ID":     key,
        "APCA-API-SECRET-KEY": secret,
        "Content-Type":        "application/json",
        "Accept":              "application/json",
    }

def is_configured() -> bool:
    key, secret = _get_creds()
    return bool(key and secret)


# ─────────────────────────────────────────────────────────────
# OCC SYMBOL BUILDER
# ─────────────────────────────────────────────────────────────

def build_occ_symbol(ticker: str, expiry: str, option_type: str, strike: float) -> str:
    """
    Build the OCC option symbol used by Alpaca.
    ticker:      e.g. "AAPL"
    expiry:      "YYYY-MM-DD"
    option_type: "CALL" or "PUT"
    strike:      e.g. 190.0

    Output: "AAPL240119C00190000"
    """
    dt  = datetime.strptime(expiry, "%Y-%m-%d")
    ymd = dt.strftime("%y%m%d")                        # 6-digit YYMMDD
    cp  = "C" if option_type.upper() == "CALL" else "P"
    # Strike in thousandths, zero-padded to 8 digits
    strike_int = int(round(strike * 1000))
    strike_str = str(strike_int).zfill(8)
    return f"{ticker.upper()}{ymd}{cp}{strike_str}"


# ─────────────────────────────────────────────────────────────
# ACCOUNT
# ─────────────────────────────────────────────────────────────

def get_account() -> dict:
    """Return Alpaca paper account details (cash, buying power, equity, etc.)."""
    if not is_configured():
        return {"error": "Alpaca API keys not configured"}
    try:
        r = httpx.get(f"{ALPACA_PAPER_BASE}/v2/account", headers=_headers(), timeout=10)
        r.raise_for_status()
        d = r.json()
        return {
            "status":         d.get("status"),
            "equity":         float(d.get("equity", 0)),
            "cash":           float(d.get("cash", 0)),
            "buying_power":   float(d.get("options_buying_power") or d.get("buying_power", 0)),
            "day_trade_count": int(d.get("daytrade_count", 0)),
            "options_approved_level": int(d.get("options_approved_level", 0)),
            "pattern_day_trader": d.get("pattern_day_trader", False),
            "currency":       d.get("currency", "USD"),
        }
    except httpx.HTTPStatusError as e:
        return {"error": f"Alpaca API error {e.response.status_code}: {e.response.text}"}
    except Exception as e:
        return {"error": str(e)}


# ─────────────────────────────────────────────────────────────
# POSITIONS
# ─────────────────────────────────────────────────────────────

def get_positions() -> list[dict]:
    """Return all open positions on the paper account."""
    if not is_configured():
        return []
    try:
        r = httpx.get(f"{ALPACA_PAPER_BASE}/v2/positions", headers=_headers(), timeout=10)
        r.raise_for_status()
        positions = r.json()
        result = []
        for p in positions:
            result.append({
                "symbol":       p.get("symbol"),
                "qty":          int(float(p.get("qty", 0))),
                "side":         p.get("side"),               # long / short
                "avg_entry":    float(p.get("avg_entry_price", 0)),
                "current_price":float(p.get("current_price", 0)),
                "market_value": float(p.get("market_value", 0)),
                "unrealized_pl":float(p.get("unrealized_pl", 0)),
                "unrealized_plpc": float(p.get("unrealized_plpc", 0)),
                "asset_class":  p.get("asset_class"),        # "us_option" | "us_equity"
            })
        return result
    except Exception as e:
        return [{"error": str(e)}]


def get_orders(status: str = "open") -> list[dict]:
    """Return recent orders. status: 'open' | 'closed' | 'all'"""
    if not is_configured():
        return []
    try:
        r = httpx.get(
            f"{ALPACA_PAPER_BASE}/v2/orders",
            headers=_headers(),
            params={"status": status, "limit": 50, "direction": "desc"},
            timeout=10,
        )
        r.raise_for_status()
        orders = r.json()
        result = []
        for o in orders:
            result.append({
                "id":           o.get("id"),
                "client_order_id": o.get("client_order_id"),
                "symbol":       o.get("symbol"),
                "status":       o.get("status"),
                "side":         o.get("side"),
                "qty":          o.get("qty"),
                "filled_qty":   o.get("filled_qty"),
                "order_type":   o.get("type"),
                "filled_avg_price": o.get("filled_avg_price"),
                "submitted_at": o.get("submitted_at"),
                "filled_at":    o.get("filled_at"),
                "legs":         o.get("legs", []),
                "strategy":     o.get("client_order_id", "").split("|")[0] if o.get("client_order_id") else "",
            })
        return result
    except Exception as e:
        return [{"error": str(e)}]


# ─────────────────────────────────────────────────────────────
# ORDER PLACEMENT
# ─────────────────────────────────────────────────────────────

def _position_intent(action: str) -> str:
    """Convert engine action (BUY/SELL) to Alpaca position_intent for opening."""
    return "buy_to_open" if action.upper() == "BUY" else "sell_to_open"


def _leg_premium_mid(leg: dict) -> float:
    """Per-share premium from engine leg (mid preferred, else bid/ask midpoint)."""
    for k in ("mid_price", "mid"):
        v = leg.get(k)
        if v is not None:
            try:
                x = float(v)
                if x > 0:
                    return x
            except (TypeError, ValueError):
                pass
    try:
        bid = float(leg.get("bid") or 0)
        ask = float(leg.get("ask") or 0)
        if bid > 0 and ask > 0:
            return round((bid + ask) / 2, 4)
        if ask > 0:
            return ask
        if bid > 0:
            return bid
    except (TypeError, ValueError):
        pass
    return 0.0


def _mleg_net_limit_price(legs: list[dict]) -> float | None:
    """
    Alpaca multileg limit_price: positive = net debit (pay), negative = net credit (receive).
    BUY legs pay premium (+), SELL legs receive (-).
    """
    net = 0.0
    for leg in legs:
        px = _leg_premium_mid(leg)
        if px <= 0:
            return None
        if leg.get("action", "").upper() == "BUY":
            net += px
        else:
            net -= px
    return round(net, 2)


def place_multileg_order(
    ticker: str,
    strategy: str,
    legs: list[dict],           # engine OptionLeg dicts: {action, option_type, strike, expiry, ...}
    contracts: int = 1,
    order_note: str = "",
) -> dict:
    """
    Place a multi-leg options order on Alpaca paper account.

    legs: list of dicts with keys: action, option_type, strike, expiry
    contracts: number of contracts (1 = 100 shares)

    Returns: Alpaca order response dict or {"error": ...}
    """
    if not is_configured():
        return {"error": "Alpaca API keys not configured. Add ALPACA_API_KEY and ALPACA_SECRET_KEY to .env"}

    if not legs:
        return {"error": "No legs provided"}

    # Build OCC symbols for each leg
    order_legs = []
    for leg in legs:
        try:
            occ = build_occ_symbol(
                ticker       = ticker,
                expiry       = leg["expiry"],
                option_type  = leg["option_type"],
                strike       = float(leg["strike"]),
            )
        except (KeyError, ValueError) as e:
            return {"error": f"Failed to build OCC symbol: {e}"}

        order_legs.append({
            "symbol":           occ,
            "side":             "buy" if leg["action"].upper() == "BUY" else "sell",
            "ratio_qty":        "1",
            "position_intent":  _position_intent(leg["action"]),
        })

    # Unique client_order_id for tracking: "strategy|ticker|timestamp"
    ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    client_id = f"{strategy[:20]}|{ticker}|{ts}"
    if order_note:
        client_id += f"|{order_note[:20]}"

    # Options *market* orders are RTH-only on Alpaca; limit orders work outside regular hours.
    net_lp = _mleg_net_limit_price(legs)
    if net_lp is None:
        return {"error": "Cannot price limit order: missing mid/bid/ask on one or more legs"}
    # Slight cushion vs marked mids so the resting limit is more likely to fill if quotes move.
    if net_lp >= 0:
        limit_price = round(max(net_lp * 1.03, net_lp + 0.02), 2)
    else:
        limit_price = round(max(net_lp * 0.98, net_lp + 0.02), 2)

    # Root-level `symbol` must NOT be set for mleg (underlying ticker is rejected — see Alpaca API).
    # Root-level `side` is also omitted for mleg; each leg carries side + position_intent.
    payload: dict = {
        "qty":              str(contracts),
        "type":             "limit",
        "limit_price":      str(limit_price),
        "time_in_force":    "day",
        "order_class":      "mleg",
        "client_order_id":  client_id,
        "legs":             order_legs,
    }

    try:
        r = httpx.post(
            f"{ALPACA_PAPER_BASE}/v2/orders",
            headers=_headers(),
            json=payload,
            timeout=15,
        )

        if r.status_code in (400, 422):
            try:
                detail = r.json()
                msg = detail.get("message", r.text)
            except Exception:
                msg = r.text
            return {"error": f"Order rejected: {msg}"}

        r.raise_for_status()
        resp = r.json()

        return {
            "ok":             True,
            "order_id":       resp.get("id"),
            "client_order_id": resp.get("client_order_id"),
            "status":         resp.get("status"),
            "symbol":         resp.get("symbol"),
            "qty":            resp.get("qty"),
            "submitted_at":   resp.get("submitted_at"),
            "legs":           [
                {
                    "symbol": lg.get("symbol"),
                    "side":   lg.get("side"),
                    "qty":    lg.get("qty"),
                    "status": lg.get("status"),
                }
                for lg in resp.get("legs", [])
            ],
        }

    except httpx.HTTPStatusError as e:
        try:
            msg = e.response.json().get("message", e.response.text)
        except Exception:
            msg = e.response.text
        return {"error": f"HTTP {e.response.status_code}: {msg}"}
    except Exception as e:
        return {"error": str(e)}


def place_single_leg_order(
    ticker: str,
    strategy: str,
    leg: dict,
    contracts: int = 1,
) -> dict:
    """Place a single-leg options order (Long Call, Long Put, Short Put, Covered Call)."""
    if not is_configured():
        return {"error": "Alpaca API keys not configured"}

    try:
        occ = build_occ_symbol(ticker, leg["expiry"], leg["option_type"], float(leg["strike"]))
    except (KeyError, ValueError) as e:
        return {"error": f"Bad leg data: {e}"}

    side = "buy" if leg["action"].upper() == "BUY" else "sell"
    ts   = datetime.utcnow().strftime("%Y%m%d%H%M%S")

    px = _leg_premium_mid(leg)
    if px <= 0:
        return {"error": "Cannot price limit order: missing mid/bid/ask on leg"}

    # Same RTH restriction as multileg — use limit priced from chain mids.
    if side == "buy":
        limit_px = round(max(px * 1.03, px + 0.02), 2)
    else:
        limit_px = round(max(px * 0.98, px - 0.02), 2)

    payload = {
        "symbol":          occ,
        "qty":             str(contracts),
        "side":            side,
        "type":            "limit",
        "limit_price":     str(limit_px),
        "time_in_force":   "day",
        "client_order_id": f"{strategy[:20]}|{ticker}|{ts}",
    }

    try:
        r = httpx.post(
            f"{ALPACA_PAPER_BASE}/v2/orders",
            headers=_headers(),
            json=payload,
            timeout=15,
        )
        if r.status_code in (400, 422):
            return {"error": f"Order rejected: {r.json().get('message', r.text)}"}
        r.raise_for_status()
        resp = r.json()
        return {
            "ok":           True,
            "order_id":     resp.get("id"),
            "status":       resp.get("status"),
            "symbol":       resp.get("symbol"),
            "qty":          resp.get("qty"),
            "submitted_at": resp.get("submitted_at"),
        }
    except httpx.HTTPStatusError as e:
        try:
            msg = e.response.json().get("message", e.response.text)
        except Exception:
            msg = e.response.text
        return {"error": f"HTTP {e.response.status_code}: {msg}"}
    except Exception as e:
        return {"error": str(e)}


def cancel_order(order_id: str) -> dict:
    """Cancel an open order by ID."""
    if not is_configured():
        return {"error": "Alpaca API keys not configured"}
    try:
        r = httpx.delete(
            f"{ALPACA_PAPER_BASE}/v2/orders/{order_id}",
            headers=_headers(),
            timeout=10,
        )
        if r.status_code == 204:
            return {"ok": True, "cancelled": order_id}
        r.raise_for_status()
        return {"ok": True}
    except httpx.HTTPStatusError as e:
        return {"error": f"HTTP {e.response.status_code}: {e.response.text}"}
    except Exception as e:
        return {"error": str(e)}


def close_position(symbol: str) -> dict:
    """Close (liquidate) an open position by OCC symbol or underlying ticker."""
    if not is_configured():
        return {"error": "Alpaca API keys not configured"}
    try:
        r = httpx.delete(
            f"{ALPACA_PAPER_BASE}/v2/positions/{symbol}",
            headers=_headers(),
            timeout=10,
        )
        if r.status_code == 204:
            return {"ok": True, "closed": symbol}
        r.raise_for_status()
        resp = r.json()
        return {"ok": True, "order_id": resp.get("id"), "status": resp.get("status")}
    except httpx.HTTPStatusError as e:
        return {"error": f"HTTP {e.response.status_code}: {e.response.text}"}
    except Exception as e:
        return {"error": str(e)}


# ─────────────────────────────────────────────────────────────
# SMART ORDER ROUTER — single entry point for the engine
# ─────────────────────────────────────────────────────────────

SINGLE_LEG_STRATEGIES = {"Long Call", "Long Put", "Short Put", "Covered Call"}

def execute_recommendation(
    ticker: str,
    strategy: str,
    legs: list[dict],
    contracts: int = 1,
) -> dict:
    """
    Route a recommendation to the correct order type:
    - 1 leg → single-leg order
    - 2+ legs → multi-leg (mleg) order
    """
    if len(legs) == 1 or strategy in SINGLE_LEG_STRATEGIES:
        return place_single_leg_order(ticker, strategy, legs[0], contracts)
    else:
        return place_multileg_order(ticker, strategy, legs, contracts)
