"""
Immutable calculation vault primitives.

This module is intentionally small and engine-agnostic. Trading engines can keep
their current implementations while new adapters start writing completed outputs
as frozen snapshots with explicit engine/formula versions.
"""
from __future__ import annotations

import hashlib
import json
import sqlite3
import time
import uuid
from typing import Any


CURRENT_FORMULA_PACK_VERSION = "formula-pack-2026.07"
CURRENT_METRIC_DEFINITIONS_VERSION = "metric-definitions-2026.07.1"
CALCULATION_ROUTER_VERSION = "calculation-router-2026.07"
TRADE_WORKSHEET_ENGINE_VERSION = "trade-worksheet-engine-2026.07"


SUPPORTED_CALCULATION_RUN_TYPES: dict[str, dict[str, Any]] = {
    "trade_worksheet": {
        "runType": "trade_worksheet",
        "label": "Trade Worksheet",
        "description": "Pre-trade options worksheet calculation with frozen risk, payoff, probability, and strategy-comparison output.",
        "engineVersion": TRADE_WORKSHEET_ENGINE_VERSION,
        "formulaPackVersion": CURRENT_FORMULA_PACK_VERSION,
        "metricDefinitionsVersion": CURRENT_METRIC_DEFINITIONS_VERSION,
        "snapshotSupported": True,
        "status": "active",
    }
}


DEFAULT_METRIC_DEFINITIONS: list[dict[str, Any]] = [
    {
        "metricId": "trade_quality_score",
        "label": "Trade Quality",
        "category": "score",
        "unit": "score_0_100",
        "formulaId": "trade_quality_score",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Overall quality score from the active backend engine.",
        "longDescription": "A normalized 0-100 score produced by the backend engine for the current trade context. The UI should display this value, not recompute it.",
        "inputsUsed": ["engine_output"],
        "displayRules": {"precision": 0, "higherIsBetter": True},
    },
    {
        "metricId": "max_profit",
        "label": "Max Profit",
        "category": "risk_reward",
        "unit": "usd",
        "formulaId": "option_strategy_payoff",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Maximum estimated profit for the selected structure.",
        "longDescription": "Calculated by the backend using the selected option legs, premiums, strikes, expiration, and strategy type.",
        "inputsUsed": ["legs", "strategy", "premium", "contracts"],
        "displayRules": {"precision": 2, "tone": "profit"},
    },
    {
        "metricId": "max_loss",
        "label": "Max Loss",
        "category": "risk_reward",
        "unit": "usd",
        "formulaId": "option_strategy_payoff",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Maximum estimated loss for the selected structure.",
        "longDescription": "Calculated by the backend using the selected option legs, premiums, strikes, expiration, and strategy type.",
        "inputsUsed": ["legs", "strategy", "premium", "contracts"],
        "displayRules": {"precision": 2, "tone": "risk"},
    },
    {
        "metricId": "breakeven",
        "label": "Breakeven",
        "category": "risk_reward",
        "unit": "price",
        "formulaId": "option_strategy_payoff",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Underlying price where estimated P&L reaches breakeven.",
        "longDescription": "Calculated by the backend from the selected strategy's strike and net premium rules.",
        "inputsUsed": ["strategy", "strikes", "net_premium"],
        "displayRules": {"precision": 2, "tone": "neutral"},
    },
    {
        "metricId": "probability_of_profit",
        "label": "Probability of Profit",
        "category": "probability",
        "unit": "percent",
        "formulaId": "probability_model",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Backend estimate of the probability the trade finishes profitable.",
        "longDescription": "Generated by the backend probability model for the selected strategy and market inputs. It is an estimate, not a guarantee.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte", "strategy"],
        "displayRules": {"precision": 0, "higherIsBetter": True},
    },
    {
        "metricId": "expected_value",
        "label": "Expected Value",
        "category": "probability",
        "unit": "usd",
        "formulaId": "expected_value",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Probability-weighted expected return.",
        "longDescription": "Calculated by the backend using estimated win/loss scenarios and probability assumptions for the selected contract.",
        "inputsUsed": ["probability_of_profit", "max_profit", "max_loss", "scenario_outputs"],
        "displayRules": {"precision": 2, "tone": "profit_loss"},
    },
    {
        "metricId": "capital_required",
        "label": "Capital Required",
        "category": "risk",
        "unit": "usd",
        "formulaId": "capital_requirement",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated buying power needed for the selected trade.",
        "longDescription": "Calculated by the backend from strategy type, contracts, premiums, spread width, and cash-secured obligations where applicable.",
        "inputsUsed": ["strategy", "contracts", "premium", "spread_width", "strike"],
        "displayRules": {"precision": 2, "tone": "risk"},
    },
    {
        "metricId": "theta_per_day",
        "label": "Theta Per Day",
        "category": "greeks",
        "unit": "usd_per_day",
        "formulaId": "black_scholes_greeks",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated daily time-decay impact.",
        "longDescription": "Calculated by the backend option model from underlying price, strike, implied volatility, and days to expiration, then scaled by contract count.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte", "contracts"],
        "displayRules": {"precision": 2, "tone": "risk"},
    },
    {
        "metricId": "delta",
        "label": "Delta",
        "category": "greeks",
        "unit": "decimal",
        "formulaId": "black_scholes_greeks",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated option sensitivity to a $1 underlying move.",
        "longDescription": "Calculated by the backend option model for the selected contract or primary leg.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte", "option_type"],
        "displayRules": {"precision": 4, "tone": "neutral"},
    },
    {
        "metricId": "gamma",
        "label": "Gamma",
        "category": "greeks",
        "unit": "decimal",
        "formulaId": "black_scholes_greeks",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated rate of change in delta.",
        "longDescription": "Calculated by the backend option model. Gamma shows how quickly delta can change as the underlying moves; short-dated contracts usually carry higher gamma risk.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte"],
        "displayRules": {"precision": 6, "tone": "risk"},
    },
    {
        "metricId": "vega",
        "label": "Vega",
        "category": "greeks",
        "unit": "usd_per_iv_point",
        "formulaId": "black_scholes_greeks",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated option sensitivity to a one-point IV change.",
        "longDescription": "Calculated by the backend option model. Vega estimates how much option value changes when implied volatility moves by one percentage point.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte"],
        "displayRules": {"precision": 4, "tone": "neutral"},
    },
    {
        "metricId": "iv_rank",
        "label": "IV Rank",
        "category": "volatility",
        "unit": "percent",
        "formulaId": "implied_volatility_rank",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Relative implied volatility level used by the backend.",
        "longDescription": "Provided by market data or calculated by the backend volatility service and used as an input to option pricing and strategy suitability.",
        "inputsUsed": ["option_chain", "historical_iv_range"],
        "displayRules": {"precision": 1, "higherIsBetter": False},
    },
    {
        "metricId": "risk_level",
        "label": "Risk Level",
        "category": "risk",
        "unit": "label",
        "formulaId": "worksheet_risk_level",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Backend risk classification for the selected worksheet trade.",
        "longDescription": "Derived by the backend from the worksheet score and selected strategy risk characteristics. It is display-only and should not be recalculated in the UI.",
        "inputsUsed": ["trade_quality_score", "strategy", "max_loss"],
        "displayRules": {"tone": "risk"},
    },
    {
        "metricId": "probability_itm",
        "label": "Probability ITM",
        "category": "probability",
        "unit": "percent",
        "formulaId": "probability_model",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Backend estimate that the contract expires in the money.",
        "longDescription": "Generated by the backend option model from underlying price, strike, implied volatility, and time to expiration.",
        "inputsUsed": ["underlying_price", "strike", "iv", "dte", "option_type"],
        "displayRules": {"precision": 1, "higherIsBetter": True},
    },
    {
        "metricId": "probability_otm",
        "label": "Probability OTM",
        "category": "probability",
        "unit": "percent",
        "formulaId": "probability_model",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Backend estimate that the contract expires out of the money.",
        "longDescription": "Generated by the backend option model as the complement to probability ITM for the selected contract.",
        "inputsUsed": ["probability_itm"],
        "displayRules": {"precision": 1, "higherIsBetter": False},
    },
    {
        "metricId": "expected_return",
        "label": "Expected Return",
        "category": "probability",
        "unit": "percent",
        "formulaId": "expected_value",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Expected value normalized by capital at risk.",
        "longDescription": "Calculated by the backend from expected value divided by the scenario capital basis for the selected trade.",
        "inputsUsed": ["expected_value", "capital_required", "max_loss"],
        "displayRules": {"precision": 1, "tone": "profit_loss"},
    },
    {
        "metricId": "expected_drawdown",
        "label": "Expected Drawdown",
        "category": "risk",
        "unit": "usd",
        "formulaId": "expected_drawdown",
        "formulaVersion": CURRENT_FORMULA_PACK_VERSION,
        "shortDescription": "Estimated drawdown used for pre-trade risk planning.",
        "longDescription": "Calculated by the backend scenario model as a conservative planning loss based on the selected trade's capital basis.",
        "inputsUsed": ["capital_required", "max_loss", "scenario_outputs"],
        "displayRules": {"precision": 2, "tone": "risk"},
    },
]


TRADE_WORKSHEET_METRIC_IDS = [
    "trade_quality_score",
    "max_profit",
    "max_loss",
    "breakeven",
    "probability_of_profit",
    "expected_value",
    "capital_required",
    "theta_per_day",
    "delta",
    "gamma",
    "vega",
    "iv_rank",
    "risk_level",
    "probability_itm",
    "probability_otm",
    "expected_return",
    "expected_drawdown",
]


def canonical_json(value: Any) -> str:
    """Stable JSON representation used for hashing snapshot inputs/outputs."""
    return json.dumps(value, sort_keys=True, separators=(",", ":"), default=str)


def sha256_json(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def now_ms() -> int:
    return int(time.time() * 1000)


def _normalize_owner_email(owner_email: str | None) -> str:
    return (owner_email or "").strip().lower()


def _ensure_column(conn: sqlite3.Connection, table: str, column: str, definition: str) -> None:
    columns = {row["name"] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    if column not in columns:
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {definition}")


def ensure_calculation_vault_schema(conn: sqlite3.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS calculation_runs (
            run_id TEXT PRIMARY KEY,
            run_type TEXT NOT NULL,
            status TEXT NOT NULL,
            engine_version TEXT NOT NULL,
            formula_pack_version TEXT NOT NULL,
            owner_email TEXT NOT NULL DEFAULT '',
            input_hash TEXT NOT NULL,
            output_hash TEXT NOT NULL DEFAULT '',
            snapshot_id TEXT,
            input_json TEXT NOT NULL,
            error TEXT NOT NULL DEFAULT '',
            created_at_ms INTEGER NOT NULL,
            completed_at_ms INTEGER,
            FOREIGN KEY(snapshot_id) REFERENCES calculation_snapshots(snapshot_id)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS calculation_snapshots (
            snapshot_id TEXT PRIMARY KEY,
            run_id TEXT NOT NULL,
            run_type TEXT NOT NULL,
            engine_version TEXT NOT NULL,
            formula_pack_version TEXT NOT NULL,
            metric_definitions_version TEXT NOT NULL,
            owner_email TEXT NOT NULL DEFAULT '',
            input_hash TEXT NOT NULL,
            output_hash TEXT NOT NULL,
            input_json TEXT NOT NULL,
            output_json TEXT NOT NULL,
            metric_definitions_json TEXT NOT NULL DEFAULT '[]',
            created_at_ms INTEGER NOT NULL,
            frozen_at_ms INTEGER NOT NULL,
            UNIQUE(run_id),
            FOREIGN KEY(run_id) REFERENCES calculation_runs(run_id)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS calculation_snapshot_audit_log (
            audit_id TEXT PRIMARY KEY,
            snapshot_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            event_json TEXT NOT NULL DEFAULT '{}',
            created_at_ms INTEGER NOT NULL,
            FOREIGN KEY(snapshot_id) REFERENCES calculation_snapshots(snapshot_id)
        )
        """
    )
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS metric_definitions (
            metric_id TEXT NOT NULL,
            formula_version TEXT NOT NULL,
            definition_json TEXT NOT NULL,
            created_at_ms INTEGER NOT NULL,
            PRIMARY KEY(metric_id, formula_version)
        )
        """
    )
    _ensure_column(conn, "calculation_runs", "owner_email", "TEXT NOT NULL DEFAULT ''")
    _ensure_column(conn, "calculation_snapshots", "owner_email", "TEXT NOT NULL DEFAULT ''")
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_calculation_runs_type_created ON calculation_runs(run_type, created_at_ms DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_calculation_snapshots_type_created ON calculation_snapshots(run_type, created_at_ms DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_calculation_runs_owner_created ON calculation_runs(owner_email, created_at_ms DESC)"
    )
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_calculation_snapshots_owner_created ON calculation_snapshots(owner_email, created_at_ms DESC)"
    )
    conn.execute(
        """
        CREATE TRIGGER IF NOT EXISTS calculation_snapshots_no_update
        BEFORE UPDATE ON calculation_snapshots
        BEGIN
            SELECT RAISE(ABORT, 'calculation_snapshots are immutable');
        END
        """
    )
    conn.execute(
        """
        CREATE TRIGGER IF NOT EXISTS calculation_snapshots_no_delete
        BEFORE DELETE ON calculation_snapshots
        BEGIN
            SELECT RAISE(ABORT, 'calculation_snapshots are immutable');
        END
        """
    )
    conn.execute(
        """
        CREATE TRIGGER IF NOT EXISTS calculation_snapshot_audit_log_no_update
        BEFORE UPDATE ON calculation_snapshot_audit_log
        BEGIN
            SELECT RAISE(ABORT, 'calculation_snapshot_audit_log is append-only');
        END
        """
    )
    conn.execute(
        """
        CREATE TRIGGER IF NOT EXISTS calculation_snapshot_audit_log_no_delete
        BEFORE DELETE ON calculation_snapshot_audit_log
        BEGIN
            SELECT RAISE(ABORT, 'calculation_snapshot_audit_log is append-only');
        END
        """
    )
    seed_metric_definitions(conn)


def seed_metric_definitions(conn: sqlite3.Connection) -> None:
    created = now_ms()
    for definition in DEFAULT_METRIC_DEFINITIONS:
        conn.execute(
            """
            INSERT OR IGNORE INTO metric_definitions (
                metric_id, formula_version, definition_json, created_at_ms
            ) VALUES (?, ?, ?, ?)
            """,
            (
                str(definition["metricId"]),
                str(definition["formulaVersion"]),
                canonical_json(definition),
                created,
            ),
        )


def resolve_metric_definitions(metric_ids: list[str] | tuple[str, ...] | set[str]) -> list[dict[str, Any]]:
    """Return metric definitions in the requested order, skipping unknown IDs."""
    requested = [str(metric_id) for metric_id in metric_ids]
    by_id = {str(definition["metricId"]): definition for definition in DEFAULT_METRIC_DEFINITIONS}
    return [by_id[metric_id] for metric_id in requested if metric_id in by_id]


def trade_worksheet_metric_definitions() -> list[dict[str, Any]]:
    """Metric definitions used by the Trade Worksheet response contract."""
    return resolve_metric_definitions(TRADE_WORKSHEET_METRIC_IDS)


def list_supported_calculation_run_types() -> list[dict[str, Any]]:
    """Return the public calculation-run registry in stable order."""
    return [dict(SUPPORTED_CALCULATION_RUN_TYPES[key]) for key in sorted(SUPPORTED_CALCULATION_RUN_TYPES)]


def _connect():
    from storage import _connect as storage_connect

    return storage_connect()


def create_calculation_snapshot(
    *,
    run_type: str,
    input_payload: dict[str, Any],
    output_payload: dict[str, Any],
    engine_version: str,
    owner_email: str | None = None,
    formula_pack_version: str = CURRENT_FORMULA_PACK_VERSION,
    metric_definitions_version: str = CURRENT_METRIC_DEFINITIONS_VERSION,
    metric_definitions: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Insert a completed run and immutable snapshot. Never updates existing rows."""
    run_id = str(uuid.uuid4())
    snapshot_id = str(uuid.uuid4())
    created = now_ms()
    input_hash = sha256_json(input_payload)
    output_hash = sha256_json(output_payload)
    metric_defs = metric_definitions if metric_definitions is not None else DEFAULT_METRIC_DEFINITIONS
    owner = _normalize_owner_email(owner_email)
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        conn.execute(
            """
            INSERT INTO calculation_runs (
                run_id, run_type, status, engine_version, formula_pack_version,
                owner_email, input_hash, output_hash, snapshot_id, input_json,
                created_at_ms, completed_at_ms
            ) VALUES (?, ?, 'COMPLETED', ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                run_id,
                run_type,
                engine_version,
                formula_pack_version,
                owner,
                input_hash,
                output_hash,
                snapshot_id,
                canonical_json(input_payload),
                created,
                created,
            ),
        )
        conn.execute(
            """
            INSERT INTO calculation_snapshots (
                snapshot_id, run_id, run_type, engine_version, formula_pack_version,
                metric_definitions_version, owner_email, input_hash, output_hash,
                input_json, output_json, metric_definitions_json,
                created_at_ms, frozen_at_ms
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                snapshot_id,
                run_id,
                run_type,
                engine_version,
                formula_pack_version,
                metric_definitions_version,
                owner,
                input_hash,
                output_hash,
                canonical_json(input_payload),
                canonical_json(output_payload),
                canonical_json(metric_defs),
                created,
                created,
            ),
        )
        conn.execute(
            """
            INSERT INTO calculation_snapshot_audit_log (
                audit_id, snapshot_id, event_type, event_json, created_at_ms
            ) VALUES (?, ?, 'SNAPSHOT_FROZEN', ?, ?)
            """,
            (
                str(uuid.uuid4()),
                snapshot_id,
                canonical_json({"runId": run_id, "ownerEmail": owner, "inputHash": input_hash, "outputHash": output_hash}),
                created,
            ),
        )
    loaded = get_calculation_snapshot(snapshot_id)
    assert loaded is not None
    return loaded


def create_failed_calculation_run(
    *,
    run_type: str,
    input_payload: dict[str, Any],
    error: str,
    engine_version: str,
    owner_email: str | None = None,
    formula_pack_version: str = CURRENT_FORMULA_PACK_VERSION,
) -> dict[str, Any]:
    """Insert a failed calculation run for auditability. No snapshot is created."""
    run_id = str(uuid.uuid4())
    created = now_ms()
    input_hash = sha256_json(input_payload)
    owner = _normalize_owner_email(owner_email)
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        conn.execute(
            """
            INSERT INTO calculation_runs (
                run_id, run_type, status, engine_version, formula_pack_version,
                owner_email, input_hash, output_hash, snapshot_id, input_json,
                error, created_at_ms, completed_at_ms
            ) VALUES (?, ?, 'FAILED', ?, ?, ?, ?, '', NULL, ?, ?, ?, ?)
            """,
            (
                run_id,
                run_type,
                engine_version,
                formula_pack_version,
                owner,
                input_hash,
                canonical_json(input_payload),
                error,
                created,
                created,
            ),
        )
    loaded = get_calculation_run(run_id)
    assert loaded is not None
    return loaded


def _decode_row(row: sqlite3.Row | None) -> dict[str, Any] | None:
    if row is None:
        return None
    data = dict(row)
    for key in ("input_json", "output_json", "metric_definitions_json", "event_json", "definition_json"):
        if key in data:
            try:
                data[key[:-5] if key.endswith("_json") else key] = json.loads(data[key] or "{}")
            except (TypeError, json.JSONDecodeError):
                data[key[:-5] if key.endswith("_json") else key] = {} if key != "metric_definitions_json" else []
            data.pop(key, None)
    return data


def get_calculation_run(run_id: str, owner_email: str | None = None) -> dict[str, Any] | None:
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        if owner_email is None:
            row = conn.execute(
                "SELECT * FROM calculation_runs WHERE run_id = ?",
                (run_id.strip(),),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM calculation_runs WHERE run_id = ? AND owner_email = ?",
                (run_id.strip(), _normalize_owner_email(owner_email)),
            ).fetchone()
    return _decode_row(row)


def get_calculation_snapshot(snapshot_id: str, owner_email: str | None = None) -> dict[str, Any] | None:
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        if owner_email is None:
            row = conn.execute(
                "SELECT * FROM calculation_snapshots WHERE snapshot_id = ?",
                (snapshot_id.strip(),),
            ).fetchone()
        else:
            row = conn.execute(
                "SELECT * FROM calculation_snapshots WHERE snapshot_id = ? AND owner_email = ?",
                (snapshot_id.strip(), _normalize_owner_email(owner_email)),
            ).fetchone()
    return _decode_row(row)


def verify_calculation_snapshot(snapshot_id: str, owner_email: str | None = None) -> dict[str, Any] | None:
    """Recompute stored snapshot hashes and verify run/snapshot linkage."""
    snapshot = get_calculation_snapshot(snapshot_id, owner_email=owner_email)
    if snapshot is None:
        return None

    run = get_calculation_run(str(snapshot.get("run_id") or ""), owner_email=owner_email)
    computed_input_hash = sha256_json(snapshot.get("input") or {})
    computed_output_hash = sha256_json(snapshot.get("output") or {})
    stored_input_hash = str(snapshot.get("input_hash") or "")
    stored_output_hash = str(snapshot.get("output_hash") or "")
    input_hash_matches = computed_input_hash == stored_input_hash
    output_hash_matches = computed_output_hash == stored_output_hash
    run_hash_matches = bool(
        run
        and str(run.get("input_hash") or "") == stored_input_hash
        and str(run.get("output_hash") or "") == stored_output_hash
        and str(run.get("snapshot_id") or "") == str(snapshot.get("snapshot_id") or "")
    )

    mismatches: list[str] = []
    if not input_hash_matches:
        mismatches.append("input_hash")
    if not output_hash_matches:
        mismatches.append("output_hash")
    if not run_hash_matches:
        mismatches.append("run_snapshot_link")

    return {
        "snapshot_id": snapshot["snapshot_id"],
        "run_id": snapshot["run_id"],
        "verified": input_hash_matches and output_hash_matches and run_hash_matches,
        "input_hash_matches": input_hash_matches,
        "output_hash_matches": output_hash_matches,
        "run_hash_matches": run_hash_matches,
        "stored_input_hash": stored_input_hash,
        "computed_input_hash": computed_input_hash,
        "stored_output_hash": stored_output_hash,
        "computed_output_hash": computed_output_hash,
        "mismatches": mismatches,
        "verified_at_ms": now_ms(),
    }


def list_calculation_snapshot_audit_log(snapshot_id: str, owner_email: str | None = None) -> list[dict[str, Any]] | None:
    """Return audit events for a snapshot, scoped through the owning snapshot row."""
    snapshot = get_calculation_snapshot(snapshot_id, owner_email=owner_email)
    if snapshot is None:
        return None

    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        rows = conn.execute(
            """
            SELECT *
            FROM calculation_snapshot_audit_log
            WHERE snapshot_id = ?
            ORDER BY created_at_ms ASC
            """,
            (snapshot_id.strip(),),
        ).fetchall()
    return [decoded for row in rows if (decoded := _decode_row(row)) is not None]


def list_calculation_runs(
    *,
    owner_email: str | None = None,
    status: str | None = None,
    run_type: str | None = None,
    limit: int = 50,
) -> list[dict[str, Any]]:
    clauses: list[str] = []
    params: list[Any] = []
    if owner_email is not None:
        clauses.append("owner_email = ?")
        params.append(_normalize_owner_email(owner_email))
    if status:
        clauses.append("status = ?")
        params.append(status.strip().upper())
    if run_type:
        clauses.append("run_type = ?")
        params.append(run_type.strip().lower())
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    params.append(max(1, min(200, int(limit))))
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        rows = conn.execute(
            f"""
            SELECT *
            FROM calculation_runs
            {where}
            ORDER BY created_at_ms DESC
            LIMIT ?
            """,
            params,
        ).fetchall()
    return [decoded for row in rows if (decoded := _decode_row(row)) is not None]


def list_metric_definitions() -> list[dict[str, Any]]:
    with _connect() as conn:
        ensure_calculation_vault_schema(conn)
        rows = conn.execute(
            """
            SELECT definition_json
            FROM metric_definitions
            ORDER BY metric_id ASC, formula_version ASC
            """
        ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        try:
            value = json.loads(row["definition_json"] or "{}")
            if isinstance(value, dict):
                out.append(value)
        except (TypeError, json.JSONDecodeError):
            continue
    return out
